In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [37]:
A = np.random.randint(0, 10, [5, 5])
A

array([[3, 4, 6, 1, 2],
       [3, 0, 2, 0, 4],
       [7, 1, 9, 7, 6],
       [2, 5, 5, 3, 6],
       [7, 6, 2, 0, 7]], dtype=int32)

In [38]:
# Sélectionner tous les nombres qui valent 10
test = A[A<5]
print(test)
display(A)

[3 4 1 2 3 0 2 0 4 1 2 3 2 0]


array([[3, 4, 6, 1, 2],
       [3, 0, 2, 0, 4],
       [7, 1, 9, 7, 6],
       [2, 5, 5, 3, 6],
       [7, 6, 2, 0, 7]], dtype=int32)

In [ ]:
#Tester plusieurs données
test = A[(A<5) & (A>1)]
print(test)
display(A)


[3 4 2 3 2 4 2 3 2]


array([[3, 4, 6, 1, 2],
       [3, 0, 2, 0, 4],
       [7, 1, 9, 7, 6],
       [2, 5, 5, 3, 6],
       [7, 6, 2, 0, 7]], dtype=int32)

array([[3, 4, 6, 1, 2],
       [3, 0, 2, 0, 4],
       [7, 1, 9, 7, 6],
       [2, 5, 5, 3, 6],
       [7, 6, 2, 0, 7]], dtype=int32)

In [48]:
np.random.seed(2)
A = np.random.randint(0, 10, [5, 5])
B = np.random.randn(5, 5)
display(A, B)
#On injecte les données de B mais on utilise le masque de A
B[A>5]

array([[8, 8, 6, 2, 8],
       [7, 2, 1, 5, 4],
       [4, 5, 7, 3, 6],
       [4, 3, 7, 6, 1],
       [3, 5, 8, 4, 6]], dtype=int32)

array([[-0.63399257, -0.35040973, -0.024108  , -1.34371499, -1.45546732],
       [ 0.34410891,  0.42486954,  1.47007746, -0.42901615, -1.07530851],
       [ 2.10708683, -0.42788042,  0.61442763,  1.10438155,  0.0319746 ],
       [ 1.18246826, -1.12076831, -0.85800742, -0.52715869,  1.11385518],
       [-1.75408685, -0.24978025,  0.54959138,  0.52170749, -1.52343212]])

array([-0.63399257, -0.35040973, -0.024108  , -1.45546732,  0.34410891,
        0.61442763,  0.0319746 , -0.85800742, -0.52715869,  0.54959138,
       -1.52343212])

In [7]:
test = 0
A = np.random.randint(0, 2, (5, 5))

array([[1, 0, 1, 1, 1],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0]], dtype=int32)